### ISSUE TITLE
erro sandbox .magento 2.1.7

### ISSUE THREAD

**Issue by marcelowu** [moip/magento2#1]
Fatal error: Uncaught Error: Call to undefined method Moip\Resource\NotificationPreferences::getToken() in /home/nihao.store/public/app/code/Moip/Magento2/Controller/Adminhtml/System/Config/Preference.php:77 Stack trace: #0 /home/nihao.store/public/app/code/Moip/Magento2/Controller/Adminhtml/System/Config/Preference.php(47): Moip\Magento2\Controller\Adminhtml\System\Config\Preference->setUrlInfoRefund(Object(Moip\Resource\NotificationPreferences)) #1 /home/nihao.store/public/vendor/magento/framework/App/Action/Action.php(102): Moip\Magento2\Controller\Adminhtml\System\Config\Preference->execute() #2 /home/nihao.store/public/vendor/magento/module-backend/App/AbstractAction.php(226): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) #3 /home/nihao.store/public/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http)) #4 /home/nihao.store/public/vendor/magento/framework/Interception/Chain/Chain.ph in /home/nihao.store/public/app/code/Moip/Magento2/Controller/Adminhtml/System/Config/Preference.php on line 77

**Comment by elisei** [comment]
Olá @marcelowu 
Acabo de atualizar o required para a versão do moip-sdk-php, no entanto novos erros irão surgir decorrentes da versão do seu Magento, recomendamos que atualize para a versão 2.2 recém lançada que corrigi vários bugs alguns deles que nos impediam de transacionar.

**Comment by marcelowu** [comment]
ok, vario meu chefe

**Comment by marcelowu** [comment]
conta fisica tambem funciona ?

**Comment by elisei** [comment]
Você diz uma conta moip em nome de pessoa física? 
Caso seja apenas se for do tipo vendedor... Caso precise use o ambiente de teste criando um conta aqui: 
https://bem-vindo-sandbox.moip.com.br
