### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by kauansoft** [moip/magento2#10]
![image](https://user-images.githubusercontent.com/27354497/38815127-9a3d28a2-4169-11e8-8726-e51c1776ed1a.png)

Quando clico em um pedido no qual o método de pagamento foi processado pelo moip (boleto, cartão, etc). Ao clicar em qualquer outro link do painel (Ex: Dashboard), essa popup é chamada (3 vezes). Os dados de acesso continuam os mesmos.

**Comment by elisei** [comment]
@kauansoft 
Não compreendi a relação desse erro com o nosso módulo, pode descreve-lo por favor?

**Comment by kauansoft** [comment]
Se você entrar em algum pedido que não foi finalizado com o moip, este aviso não ocorre.

**Comment by elisei** [comment]
@kauansoft entendo, no entanto não veja ainda relação com nosso módulo, verifique demais informações de sua aplicação e caso necessário no envie logs relacionando o erro.
