### ISSUE TITLE
Valor divergente - Magento/Moip

### ISSUE THREAD

**Issue by kauansoft** [moip/magento2#11]
Magento:

Order # 000000060

Grand Total | R$177.37
Total Paid | R$177.37
Total Refunded | R$0.00
Total Due | R$0.00
Subtotal | R$139.66
Shipping & Handling | R$37.71

-----------------------------------------------------------------------------------------------------------

ID MOIP: ORD-DY3QX8AWFF7Z

( + ) itens | R$ 139,66
( + ) acréscimos | R$ 9,76
( + ) frete | R$ 37,71
( = ) valor total | R$ 187,13

**Comment by elisei** [comment]
@kauansoft poderia por gentileza elaborar melhor a dúvida?

**Comment by kauansoft** [comment]
O valor do pedido no painel administrativo é diferente do que consta no moip.

**Comment by elisei** [comment]
@kauansoft 
Esse pedido foi feita via qual método? 
Se foi via Cartão de crédito, você verificou o valor de parcelamento ainda no checkout?

**Comment by kauansoft** [comment]
@elisei 
Sim foi feito por cartão (4x).
Esse valor de  ( + ) acréscimos | R$ 9,76 acho que é referente a essa divergência. O problema é que no setor financeiro não converge as informações.

**Comment by elisei** [comment]
@kauansoft então não há uma divergência, o valor cobrado é o devido com o juros que são aplicados certo?

**Comment by kauansoft** [comment]
@elisei O certo não seria o Magento pegar essas taxas também e acrescentar como taxas no valor final?

**Comment by elisei** [comment]
@kauansoft É uma possibilidade, no entanto o módulo não realiza tal ação no momento. 
Caso queira poderá abrir uma solicitação de recurso na nossa central em magento@moip.com.br ou ainda personalizar a aplicação diretamente em seu projeto. 
Fecharei esse issues pois não há uma divergência de valores.
