### ISSUE TITLE
Método de pagamento não é mostrado no painel de administração.

### ISSUE THREAD

**Issue by kauansoft** [moip/magento2#13]
Olá.

Criar um pedido através do painel administrativo do Magento (2.2.3) o método de pagamento do moip não é mostrado.

![image](https://user-images.githubusercontent.com/27354497/40559701-0a9cffea-602e-11e8-94ba-2f7508cd057c.png)

**Comment by elisei** [comment]
@kauansoft 

Não é oferecido apoio a pagamentos via admin.
