### ISSUE TITLE
addresses labels

### ISSUE THREAD

**Issue by leogold** [moip/magento2#14]
Não estão aparecendo os nomes dos campos de endereço. Deveria aparecer com o MOIP ou é algo que não está no modulo?

**Comment by elisei** [comment]
Olá @leogold 

Desculpe mas não compreendi o erro, pode encaminhar um print por favor?

**Comment by leogold** [comment]
Desculpe. O formato de 4 campos de endereço estão sem os nomes. Não sei se este módulo contempla esses campos já que não tem o OSC como no MOIP do magento 1.

<img width="1166" alt="screen shot 2018-05-28 at 14 37 33" src="https://user-images.githubusercontent.com/5704945/40624751-c540914c-6284-11e8-84da-e3d748500ce5.png">

**Comment by elisei** [comment]
Olá @leogold 
Então, nosso módulo é apenas uma forma de pagamento mesmo, não contempla tal sessão. 

Caso tenha novas dúvidas referente ao por favor reabra o issues :)
