### ISSUE TITLE
Moip Marketplace

### ISSUE THREAD

**Issue by Jackcar** [moip/magento2#15]
Ola, 

Estou usando o moip em meu marketplace, com a extensao do webkul, gostaria de saber se ha algum desenvolvimento acontecendo para marketplaces ou e necessario implementa-lo do zero? 

Sei que ha uma extensao do proprio webkul para o moip, mas gostaria de uma alternativa.

Obrigado.

**Comment by elisei** [comment]
Olá @Jackcar 

O Magento não dispõem de nenhuma aplicação nativa para mktplace, sendo assim é necessário uso de módulos de terceiros para tal finalidade, como é o seu caso a webkull. 

Nesse cenário, por não haver uma função nativa, não temos como fazer tal implementação (nos falta documentação do módulo, compatibilidade com outros módulos de mesma finalidade...) apenas os próprios desenvolvedores da aplicação de marketplace é que podem desenvolver tal finalidade.

**Comment by MuriloMachadoBlumenau** [comment]
Olá @Jackcar,
Também uso o módulo de Marketplace da Webkul. Gostaria de poder trocar informações com outros usuários e assim quem sabe nos ajudar mutualmente. Se tiver interesse, me procure pelo e-mail "a.murilomachado@gmail.com"
