### ISSUE TITLE
Retorno de status

### ISSUE THREAD

**Issue by leovulks** [moip/magento2#18]
Fiz um pedido no cartão de crédito com o módulo configurado em ambiente Produção, aprovou no cartão, recebi SMS da operado confirmando o pagamento, mas o status PAGO nao retornou no admin da loja, mesmo constando como pago no site do moip

**Comment by elisei** [comment]
Olá @leovulks 

A ação de pagamento não é um status e sim uma ação (emitir fatura, essa sim com status pago), veja no admin se foi gerada a faturação corretamente, caso não você pode estar com uma falha de entrega de status, para resolver desconectar a conta moip e refazer o fluxo de autorização do módulo.
