### ISSUE TITLE
Erro Moip -  Environment does not exist

### ISSUE THREAD

**Issue by henriqjunqueira** [moip/magento2#2]
Oi, esse modulo esta funcional magento2? se sim quais as versões? estou usando 2.1.8

tentei instalar e consegui instalar somente colocando os arquivos direto no app/code porque ele não instala no vendor, entretanto eu estou recebendo o seguinte erro:

1 exception(s):
Exception #0 (ReflectionException): Class Moip\Magento2\Block\Adminhtml\System\Config\Environment does not exist

Alguma solução? obrigado!

**Comment by elisei** [comment]
Olá @henriqjunqueira a versão mínima do magento é a 2.2.
O módulo está funcional e disponível para testes no url: http://159.203.170.2/
