### ISSUE TITLE
Diferença 0,01

### ISSUE THREAD

**Issue by edunogueira** [moip/magento2#20]
### Preconditions
1. moip/magento: 1.0.8
2. magento2: 2.2.4

### Steps to reproduce
1. Criei um produto virtual com o valor de R$45.99
2. Criei uma regra de desconto de produto para cobrar R$19.99
3. Realizei o pedido, foi concluído normalmente (no magento aparece o valor do pedido R$19.99).

### Expected result
1. No resumo da conta moip aparecer o pedido com o valor de R$19.99

### Actual result
1. No resumo da conta moip aparece o pedido com o valor de R$19.98

O problema está aqui:
https://github.com/moip/magento2/blob/master/Helper/Data.php#L317

![captura de tela de 2018-09-11 13 36 55](https://user-images.githubusercontent.com/7444742/45374246-e0d56180-b5c7-11e8-8dd2-a39cbb25804f.png)

**Comment by elisei** [comment]
Olá @edunogueira 

Arquivo alterado!
