### ISSUE TITLE
Payment Faile - A quantidade do item deve ser maior do que 0

### ISSUE THREAD

**Issue by gcampedelli** [moip/magento2#22]
O Moip passa todos os pagamentos no Magento 2.2.6, exceto quando o produto é configurável, cuja quantidade padrão é 0, pois o produto é formado por uma série de outros SKUs e o Moip não passa o pagamento porque pega a quantidade 0 do produto configurável e nõa a quantidade correta do produto escolhido pelas configurações.

**Comment by elisei** [comment]
@gcampedelli 

Por favor faça a atualização para essa nova versão caso o problema persista por favor nos informe!
