### ISSUE TITLE
versao magento 2.3 php 7.2 compatibilidade

### ISSUE THREAD

**Issue by wubuyun** [moip/magento2#24]
alguma previsao para versao magento 2.3 php 7.2 chefe?

**Comment by elisei** [comment]
Olá @wubuyun 

Essa versão já atende do magento 2.1 em diante! ;)

**Comment by wubuyun** [comment]
funciona 2.1 2.2 mas no 2.3 nao funciona. .eu instalei no php 7.2

**Comment by elisei** [comment]
@wubuyun 

A versão 2.3 ainda consta como developer foram testadas 2.1 a 2.2.6. Nesse caso por ser uma versão ainda em desenvolvimento é necessário aguardar a publicação para então verificarmos.

**Comment by wubuyun** [comment]
obrigado

**Comment by wubuyun** [comment]
> @wubuyun
> 
> A versão 2.3 ainda consta como developer foram testadas 2.1 a 2.2.6. Nesse caso por ser uma versão ainda em desenvolvimento é necessário aguardar a publicação para então verificarmos.

saiu a versao 2.3 php7.2

**Comment by elisei** [comment]
@wubuyun já disponível!
