### ISSUE TITLE
adicinar máscara e validação de CNPJ, CPF no magento2

### ISSUE THREAD

**Issue by wubuyun** [moip/magento2#25]
Excelente código para Máscara e Validação de CNPJ, CPF, CEP Data e Telefone
[http://www.fabiobmed.com.br/excelente-codigo-para-mascara-e-validacao-de-cnpj-cpf-cep-data-e-telefone/](http://www.fabiobmed.com.br/excelente-codigo-para-mascara-e-validacao-de-cnpj-cpf-cep-data-e-telefone/)
exemplo no pagseguro/magento2
[https://github.com/pagseguro/magento2/blob/bb6e6ea4398c4357af5711d9b3b48d44765aa134/view/frontend/web/js/model/direct-payment-validator.js](https://github.com/pagseguro/magento2/blob/bb6e6ea4398c4357af5711d9b3b48d44765aa134/view/frontend/web/js/model/direct-payment-validator.js)

**Comment by elisei** [comment]
@wubuyun 
Nosso módulo faz captura de cpf ou cpnj ou mesmo de outros campos, a captura é feita pelo checkout, deverá ser implementado nele e não em uma forma de pagamento.

**Comment by wubuyun** [comment]
ah, entendi,

**Comment by wubuyun** [comment]
e as funcoes sequinte vc vai inclementar no futuro?
Saving a credit card
Using a saved credit card
Removing a saved credit card
