### ISSUE TITLE
Instalar via composer

### ISSUE THREAD

**Issue by zehsergio** [moip/magento2#3]
instalação via composer

composer require moip/magento2

**Comment by joaolucasl** [comment]
Oi @zehsergio! Tudo bem? 

Pode explicar melhor o que você quis dizer com essa issue? Esse comando que vc passou é da biblioteca de PHP, certo? Explica melhor pra gente pra gente ajudar ou aceitar sua contribuição!

Abraços!
![👍](https://media.giphy.com/media/CvZuv5m5cKl8c/giphy.gif)

**Comment by zehsergio** [comment]
Olá,
A intenção na verdade é de vcs incluirem apenas a linha de instalação via composer.
Eu testei com essa linha de código e deu certo!
Resolvi chamar atenção de vcs para isso pois estou com alguns clientes com dificuldades para instalação manual do modulo (via pasta).

Esclarecido?

Enviado do meu iPhone

Em 19 de out de 2017, à(s) 13:19, João Lucas Lucchetta <notifications@github.com> escreveu:
