### ISSUE TITLE
Erro na instalação magento 2.1.8

### ISSUE THREAD

**Issue by fabionoa** [moip/magento2#5]
Ola Pessoal, estou tendo uma dificuldade para instalar o módulo via composer,
aparece o seguinte erro:

Using version ^2.1 for moip/moip-sdk-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for flowecommerce/pt_br ^100.0 -> satisfiable by flowecommerce/pt_br[100.0.1].
    - Conclusion: remove magento/framework 100.1.8
    - Conclusion: don't install magento/framework 100.1.8
    - flowecommerce/pt_br 100.0.1 requires magento/framework 100.0.* -> satisfiable by magento/framework[100.0.2, 100.0.3, 100.0.4, 100.0.5, 100.0.6, 100.0.7, 100.0.8, 100.0.9, 100.0.10, 100.0.11, 100.0.12, 100.0.13, 100.0.14, 100.0.15, 100.0.16, 100.0.17, 100.0.18].
    - Can only install one of: magento/framework[100.1.8, 100.0.2].
    - Can only install one of: magento/framework[100.1.8, 100.0.3].
    - Can only install one of: magento/framework[100.1.8, 100.0.4].
    - Can only install one of: magento/framework[100.1.8, 100.0.5].
    - Can only install one of: magento/framework[100.1.8, 100.0.6].
    - Can only install one of: magento/framework[100.1.8, 100.0.7].
    - Can only install one of: magento/framework[100.1.8, 100.0.8].
    - Can only install one of: magento/framework[100.1.8, 100.0.9].
    - Can only install one of: magento/framework[100.1.8, 100.0.10].
    - Can only install one of: magento/framework[100.1.8, 100.0.11].
    - Can only install one of: magento/framework[100.1.8, 100.0.12].
    - Can only install one of: magento/framework[100.1.8, 100.0.13].
    - Can only install one of: magento/framework[100.1.8, 100.0.14].
    - Can only install one of: magento/framework[100.1.8, 100.0.15].
    - Can only install one of: magento/framework[100.1.8, 100.0.16].
    - Can only install one of: magento/framework[100.1.8, 100.0.17].
    - Can only install one of: magento/framework[100.1.8, 100.0.18].
    - Installation request for magento/framework == 100.1.8.0 -> satisfiable by magento/framework[100.1.8].

Alguem poderia me ajudar???

Obrigado

**Comment by elisei** [comment]
Oi @fabionoa,

O composer está informando que a versão atual do seu magento não compatível, a mínima requerida atualmente para o projeto é a 2.2
