### ISSUE TITLE
Integrating one step checkout with moip

### ISSUE THREAD

**Issue by LeorentKelmendi** [moip/magento2#7]
I just downloaded the plugin and installed, connected to moip sandbox everything went smooth, except now when I try to make a payment with card, when I click `Plcae Order` button it wont process the payment, when I open up the console I see `Moip` it is not defined. this bug its comming from `moipcc.js` file:
 
![untitled](https://user-images.githubusercontent.com/23528898/35097698-7c8395ba-fc51-11e7-9c76-cdfc21572b77.png)

**Comment by elisei** [comment]
Hello,
Did you also get a mistake on the "boleto bancário" payment?

**Comment by LeorentKelmendi** [comment]
Hello, using that option I get this error:
Do you have any idea what is going wrong ? 
![untitled](https://user-images.githubusercontent.com/23528898/35098091-2284cd5c-fc53-11e7-9e77-b29ba6e2bcf9.png)

**Comment by elisei** [comment]
Hi @LeorentKelmendi, 
This module is exclusive to payment in Brazil and requires the processing of checkout data, you need to relate the attributes of your magento with the expected in our api, see more details at:
https://github.com/moip/magento2/wiki/Relacionamento-de-Atributos

**Comment by LeorentKelmendi** [comment]
@elisei I have configured params based on the git desription. But now I get payment failed
![untitled](https://user-images.githubusercontent.com/23528898/35106430-8029836a-fc6e-11e7-8caf-cb07ce55d9ab.png)

**Comment by elisei** [comment]
Hi @LeorentKelmendi 

By json is missing the CPF (Brazilian tax document) you can generate valid cpf here:
https://www.geradordecpf.org/

But do not forget to relate the cpf attribute to some field of the magento.

We recommend vat_id, but you can choose another one if you wish.

**Comment by LeorentKelmendi** [comment]
@elisei That worked 👍 for boleto payment. But paying by card its not working 
![untitled](https://user-images.githubusercontent.com/23528898/35108229-4b63bccc-fc73-11e7-91a6-ace7669fbb0d.png)

**Comment by elisei** [comment]
@LeorentKelmendi tks!
Are you using a native thema?

**Comment by LeorentKelmendi** [comment]
@elisei  Trying to debugg so when I write 'moip' on the console it doest show up as the file its not being included! Yes Luna .

**Comment by elisei** [comment]
@LeorentKelmendi 
Can you give me an access to this store to check the process on the frontend?

**Comment by LeorentKelmendi** [comment]
@elisei its not in production yet nor dev server. Want to check it through teamviewer ?

**Comment by elisei** [comment]
Okay, can we follow by email?
magento@moip.com.br

**Comment by LeorentKelmendi** [comment]
Thank you, I have sent you the mail @elisei
