### ISSUE TITLE
Erro ao pegar endereço

### ISSUE THREAD

**Issue by edunogueira** [moip/magento2#8]
**Pré condições**

1. Magento 2.2.1
2. Moip/Magento2 1.0

**Passos para reproduzir**

1. Adicionar somente produtos virtuais no carrinho
2. Prosseguir para checkout
3. Selecionar alguma forma de pagamento MOIP (CC ou boleto)
4. Realizar pedido

**Resultado esperado**

1. Pedido ser realizado

**Resultado atual**
Quando somente há produtos virtuais no carrinho, retorna erro. Adicionando um produto normal no meio, não há problema.
"Fatal Error: 'Uncaught Error: Call to a member function getStreet() on null in [pasta do projeto]/vendor/moip/magento2/Helper/Data.php:142
Stack trace:
n#0 [pasta do projeto]/vendor/moip/magento2/Model/PaymentMethodBoleto.php(109): MoipMagento2HelperData->generateCustomerMoip(Object(MagentoSalesModelOrderInterceptor))
n#1 [pasta do projeto]/vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php(45): MoipMagento2ModelPaymentMethodBoleto->authorize(Object(MagentoSalesModelOrderPaymentInterceptor), 104.96)
n#2 [pasta do projeto]/vendor/magento/module-sales/Model/Order/Payment/Processor.php(72): MagentoSalesModelOrderPaymentOperationsAuthorizeOperation->authorize(Object(MagentoSalesModelOrderPaymentInterceptor), true, 104.96)
n#3 [pasta do projeto]/vendor/magento/module-sales/Model/Order/Payment.php(1107): MagentoSalesModelOrderPaymentProcessor->authorize(Object(MagentoSalesModelOrderPaymentInterceptor), true, 104.96)
n#4 [pasta do projeto]/vendor/moip/magento2/Helper/Data.php' on line 142"

**Comment by elisei** [comment]
Olá @edunogueira 

Obrigado pelo contato! Este isseus foi marcado como solicitação de recurso.

Nesse caso é a aplicação de recurso para venda produtos virtuais. 

O processo será escalado e assim que possível retornaremos o contato por este issues.

**Comment by elisei** [comment]
Olá @edunogueira 

Novo recurso já se encontra disponível por favor faça o update caso necessário nos informe.

**Comment by Jackcar** [comment]
Estou utilizando o Magento 2.2.4 e este erro ainda esta ocorrendo, ha alguma solucao?

**Comment by elisei** [comment]
@Jackcar esse issues foi específico para vendas de **produto virtual** esse é também o seu cenário?
Você consegue realizar pagamentos de produtos físicos mas não de virtuais?

**Comment by Jackcar** [comment]
@elisei realmente era problema do produto virtual, mudei para simples e seguiu. Obrigado.
