### ISSUE TITLE
Payment failed

### ISSUE THREAD

**Issue by kauansoft** [moip/magento2#9]
Magento 2.2.3

Quando vou finalizar o pagamento por boleto bancário ou outro método aparece uma mensagem de erro:

"Payment failed Payment failed".

Os logs do magento não reportaram nada.

Percebi que no campo de checkout os endereços não começam apartir do 1 como no mapeamento do plugin. Sendo assim: street[0], street[1], street[2], street [3]

URL para teste:

www.hortibras.com

Podem utilizar a pesquisa "adubo" adicionar um produto e tentar fazer o checkout por boleto.

**Comment by elisei** [comment]
Olá @kauansoft 

O mapeamento de atributos é feito por vocês direto no admin em:
https://github.com/moip/magento2/wiki/Relacionamento-de-Atributos

**Comment by kauansoft** [comment]
Eu fiz, mas como eu disse, não começa no street_1 e sim no street_0, mesmo mapeando o erro persiste.

**Comment by elisei** [comment]
Olá @kauansoft 
A opção definida como 1ª linha de endereço já faz referência ao street_0 e não a posição 1 do array.

**Comment by kauansoft** [comment]
Entendi, mesmo assim não funciona, eu segui a formatação das variáveis tb.

**Comment by elisei** [comment]
@kauansoft 
Em contato com o canal magento@moip.com.br verificamos que você atribui ao campo esperado por nós em CPF como vat_id no entanto o mesmo não existe em seu cadastro.

**Comment by kauansoft** [comment]
Quando eu insiro um CNPJ em vez de um CPF, o erro persiste.

**Comment by elisei** [comment]
@kauansoft pode postar um print da configuração de relacionamento de atributos por favor?

**Comment by kauansoft** [comment]
![cnpj](https://user-images.githubusercontent.com/27354497/38215425-34a99870-369e-11e8-81e3-858ca77a33a3.jpg)
O campo company está desabilitado.

**Comment by elisei** [comment]
@kauansoft se o company está desabilita você precisa alterar o relacionamento pois ele precisa ser informado, ou ativa-lo.

**Comment by kauansoft** [comment]
Ok

Em seg, 2 de abr de 2018 às 17:51, Bruno <notifications@github.com>
escreveu:

**Comment by kauansoft** [comment]
@elisei , novamente este erro, pode verificar?
